language: go

go:
  - 1.3
  - tip

before_install:
  - go get github.com/tools/godep
  - go install -race std
  - mysql -e "create database IF NOT EXISTS test;" -uroot
script:
  - godep go test -race ./go/...
